#ifndef CONFIG_GLSL
#define CONFIG_GLSL

#define ATLAS_WIDTH 240.0
#define ATLAS_HEIGHT 240.0
#define ATLAS_FACE_WIDTH 16.0
#define ATLAS_FACE_HEIGHT 16.0
#define ATLAS_X_FACES 15.0
#define ATLAS_Y_FACES 15.0
#define VOXEL_X_BITS 5
#define VOXEL_Y_BITS 5
#define VOXEL_Z_BITS 5
#define VOXEL_U_BITS 4
#define VOXEL_V_BITS 4
#define VOXEL_DIRECTION_BITS 3
#define VOXEL_X_OFFSET (0)
#define VOXEL_Y_OFFSET (VOXEL_X_OFFSET + VOXEL_X_BITS)
#define VOXEL_Z_OFFSET (VOXEL_Y_OFFSET + VOXEL_Y_BITS)
#define VOXEL_U_OFFSET (VOXEL_Z_OFFSET + VOXEL_Z_BITS)
#define VOXEL_V_OFFSET (VOXEL_U_OFFSET + VOXEL_U_BITS)
#define VOXEL_DIRECTION_OFFSET (VOXEL_V_OFFSET + VOXEL_V_BITS)
#define VOXEL_X_MASK ((1 << VOXEL_X_BITS) - 1)
#define VOXEL_Y_MASK ((1 << VOXEL_Y_BITS) - 1)
#define VOXEL_Z_MASK ((1 << VOXEL_Z_BITS) - 1)
#define VOXEL_U_MASK ((1 << VOXEL_U_BITS) - 1)
#define VOXEL_V_MASK ((1 << VOXEL_V_BITS) - 1)
#define VOXEL_DIRECTION_MASK ((1 << VOXEL_DIRECTION_BITS) - 1)

#endif