// glslc: warning: '#pragma once' : not implemented

#ifndef CONFIG_H
#define CONFIG_H

#define APP_NAME "blocks"
#define APP_VERSION "0.0.1"
#define APP_ICON BLOCK_GRASS
#define APP_VALIDATION 1
#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 764
#define WINDOW_TITLE "blocks"

#define PLAYER_SPEED 0.02f
#define PLAYER_SUPER_SPEED 0.5f
#define PLAYER_SENSITIVITY 0.1f
#define PLAYER_X 0
#define PLAYER_Y 30
#define PLAYER_Z 0

#define ATLAS_WIDTH 256.0
#define ATLAS_HEIGHT 256.0
#define ATLAS_FACE_WIDTH 16.0
#define ATLAS_FACE_HEIGHT 16.0
#define ATLAS_X_FACES 16.0
#define ATLAS_Y_FACES 16.0

#define SHADOW_SIZE 4096
#define SHADOW_Y 30.0f
#define SHADOW_PITCH (-PI / 4.0f)
#define SHADOW_YAW (PI / 8.0f)

#define CHUNK_X 30
#define CHUNK_Y 30
#define CHUNK_Z 30
#define GROUP_CHUNKS 6
#define GROUP_X (CHUNK_X)
#define GROUP_Y (CHUNK_Y * GROUP_CHUNKS)
#define GROUP_Z (CHUNK_Z)
#define WORLD_X 30
#define WORLD_Y (GROUP_CHUNKS)
#define WORLD_Z 30
#define WORLD_GROUPS (WORLD_X * WORLD_Z)
#define WORLD_CHUNKS (WORLD_Y * WORLD_GROUPS)
#define WORLD_MAX_JOBS 3000
#define WORLD_MAX_WORKERS 4

#define DATABASE_MAX_JOBS 100
#define DATABASE_PATH "blocks.sqlite3"
#define DATABASE_TIME 1000
#define DATABASE_PLAYER 0

#define VOXEL_X_BITS 5
#define VOXEL_Y_BITS 5
#define VOXEL_Z_BITS 5
#define VOXEL_U_BITS 4
#define VOXEL_V_BITS 4
#define VOXEL_DIRECTION_BITS 3
#define VOXEL_X_OFFSET (0)
#define VOXEL_Y_OFFSET (VOXEL_X_OFFSET + VOXEL_X_BITS)
#define VOXEL_Z_OFFSET (VOXEL_Y_OFFSET + VOXEL_Y_BITS)
#define VOXEL_U_OFFSET (VOXEL_Z_OFFSET + VOXEL_Z_BITS)
#define VOXEL_V_OFFSET (VOXEL_U_OFFSET + VOXEL_U_BITS)
#define VOXEL_DIRECTION_OFFSET (VOXEL_V_OFFSET + VOXEL_V_BITS)
#define VOXEL_X_MASK ((1 << VOXEL_X_BITS) - 1)
#define VOXEL_Y_MASK ((1 << VOXEL_Y_BITS) - 1)
#define VOXEL_Z_MASK ((1 << VOXEL_Z_BITS) - 1)
#define VOXEL_U_MASK ((1 << VOXEL_U_BITS) - 1)
#define VOXEL_V_MASK ((1 << VOXEL_V_BITS) - 1)
#define VOXEL_DIRECTION_MASK ((1 << VOXEL_DIRECTION_BITS) - 1)

#define RAYCAST_STEP 0.02f
#define RAYCAST_LENGTH 10.0f

#define NOISE_SEA 30
#define NOISE_GRASS (NOISE_SEA + 1)
#define NOISE_MOUNTAIN (NOISE_GRASS + 30)
#define NOISE_SNOW (NOISE_MOUNTAIN + 40)
#define NOISE_FREQUENCY 0.005f
#define NOISE_SCALE 50.0f
#define NOISE_EXPONENTIAL 1.3f
#define NOISE_LACUNARITY 2.0f
#define NOISE_GAIN 0.5f
#define NOISE_OCTAVES 5
#define NOISE_LOW (NOISE_SEA + 10)
#define NOISE_LOW_FREQUENCY 0.01f
#define NOISE_LOW_SCALE 12.0f
#define NOISE_BIOME_FREQUENCY 0.2f
#define NOISE_BIOME_SCALE 8.0f
#define NOISE_BIOME_CLAMP 5.0f

#define BUTTON_FORWARD SDL_SCANCODE_W
#define BUTTON_BACKWARD SDL_SCANCODE_S
#define BUTTON_LEFT SDL_SCANCODE_A
#define BUTTON_RIGHT SDL_SCANCODE_D
#define BUTTON_UP SDL_SCANCODE_E
#define BUTTON_DOWN SDL_SCANCODE_Q
#define BUTTON_SPRINT SDL_SCANCODE_LCTRL
#define BUTTON_BLOCK SDL_SCANCODE_B
#define BUTTON_PAUSE SDL_SCANCODE_ESCAPE
#define BUTTON_FULLSCREEN SDL_SCANCODE_F11
#define BUTTON_PLACE SDL_BUTTON_RIGHT
#define BUTTON_BREAK SDL_BUTTON_LEFT

#endif