#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_NAME "blocks"
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define RENDERER_SIZE 1280
#define DEVICE_DEBUG false
#define WINDOW_ICON BLOCK_ROSE
#define INPUT_FORWARD SDL_SCANCODE_W
#define INPUT_BACKWARD SDL_SCANCODE_S
#define INPUT_LEFT SDL_SCANCODE_A
#define INPUT_RIGHT SDL_SCANCODE_D
#define INPUT_UP SDL_SCANCODE_E
#define INPUT_DOWN SDL_SCANCODE_Q
#define INPUT_FAST SDL_SCANCODE_LCTRL
#define INPUT_SLOW SDL_SCANCODE_LSHIFT
#define INPUT_BLOCK SDL_SCANCODE_B
#define INPUT_PAUSE SDL_SCANCODE_ESCAPE
#define INPUT_FULLSCREEN SDL_SCANCODE_F11
#define INPUT_PLACE SDL_BUTTON_RMASK
#define INPUT_BREAK SDL_BUTTON_LMASK
#define BLOCK_WIDTH 16.0f
#define ATLAS_WIDTH 512.0f
#define ATLAS_LEVELS 4
#define PLAYER_SPEED 0.015f
#define PLAYER_SENSITIVITY 0.1f
#define PLAYER_Y 60.0f
#define PLAYER_REACH 10.0f
#define SHADOW_SIZE 4096
#define SHADOW_Y 30.0f
#define SHADOW_PITCH (-PI / 4.0f)
#define SHADOW_YAW (PI / 4.0f)
#define CHUNK_X 30
#define CHUNK_Y 210
#define CHUNK_Z 30
#define WORLD_X 20
#define WORLD_Z 20
#define WORLD_CHUNKS (WORLD_X * WORLD_Z)
#define WORLD_WORKERS 4
#define DATABASE_PATH "blocks.sqlite3"
#define DATABASE_COOLDOWN 10000.0f
#define DATABASE_PLAYER 0
#define VOXEL_X_BITS 5
#define VOXEL_Y_BITS 8
#define VOXEL_Z_BITS 5
#define VOXEL_U_BITS 1
#define VOXEL_V_BITS 1
#define VOXEL_FACE_BITS 6
#define VOXEL_DIRECTION_BITS 3
#define VOXEL_SHADOW_BITS 1
#define VOXEL_SHADOWED_BITS 1
#define VOXEL_OCCLUDED_BITS 1
#define VOXEL_X_OFFSET (0)
#define VOXEL_Y_OFFSET (VOXEL_X_OFFSET + VOXEL_X_BITS)
#define VOXEL_Z_OFFSET (VOXEL_Y_OFFSET + VOXEL_Y_BITS)
#define VOXEL_U_OFFSET (VOXEL_Z_OFFSET + VOXEL_Z_BITS)
#define VOXEL_V_OFFSET (VOXEL_U_OFFSET + VOXEL_U_BITS)
#define VOXEL_FACE_OFFSET (VOXEL_V_OFFSET + VOXEL_V_BITS)
#define VOXEL_DIRECTION_OFFSET (VOXEL_FACE_OFFSET + VOXEL_FACE_BITS)
#define VOXEL_SHADOW_OFFSET (VOXEL_DIRECTION_OFFSET + VOXEL_DIRECTION_BITS)
#define VOXEL_SHADOWED_OFFSET (VOXEL_SHADOW_OFFSET + VOXEL_SHADOW_BITS)
#define VOXEL_OCCLUDED_OFFSET (VOXEL_SHADOWED_OFFSET + VOXEL_SHADOWED_BITS)
#define VOXEL_X_MASK ((1 << VOXEL_X_BITS) - 1)
#define VOXEL_Y_MASK ((1 << VOXEL_Y_BITS) - 1)
#define VOXEL_Z_MASK ((1 << VOXEL_Z_BITS) - 1)
#define VOXEL_U_MASK ((1 << VOXEL_U_BITS) - 1)
#define VOXEL_V_MASK ((1 << VOXEL_V_BITS) - 1)
#define VOXEL_FACE_MASK ((1 << VOXEL_FACE_BITS) - 1)
#define VOXEL_DIRECTION_MASK ((1 << VOXEL_DIRECTION_BITS) - 1)
#define VOXEL_SHADOW_MASK ((1 << VOXEL_SHADOW_BITS) - 1)
#define VOXEL_SHADOWED_MASK ((1 << VOXEL_SHADOWED_BITS) - 1)
#define VOXEL_OCCLUDED_MASK ((1 << VOXEL_OCCLUDED_BITS) - 1)

#endif