#pragma once

#define CHUNK_X 30
#define CHUNK_Y 30
#define CHUNK_Z 30

#define GROUP_CHUNKS 9
#define GROUP_X (CHUNK_X)
#define GROUP_Y (CHUNK_Y * GROUP_CHUNKS)
#define GROUP_Z (CHUNK_Z)

#define WORLD_X 21
#define WORLD_Y (GROUP_CHUNKS)
#define WORLD_Z 21
#define WORLD_GROUPS (WORLD_X * WORLD_Z)
#define WORLD_CHUNKS (WORLD_Y * WORLD_GROUPS)
#define WORLD_MAX_JOBS 1000
#define WORLD_MAX_WORKERS 4

#define DATABASE_MAX_JOBS 100

#define VOXEL_X_BITS 5
#define VOXEL_Y_BITS 5
#define VOXEL_Z_BITS 5
#define VOXEL_U_BITS 4
#define VOXEL_V_BITS 4
#define VOXEL_DIRECTION_BITS 3
#define VOXEL_X_OFFSET (0)
#define VOXEL_Y_OFFSET (VOXEL_X_OFFSET + VOXEL_X_BITS)
#define VOXEL_Z_OFFSET (VOXEL_Y_OFFSET + VOXEL_Y_BITS)
#define VOXEL_U_OFFSET (VOXEL_Z_OFFSET + VOXEL_Z_BITS)
#define VOXEL_V_OFFSET (VOXEL_U_OFFSET + VOXEL_U_BITS)
#define VOXEL_DIRECTION_OFFSET (VOXEL_V_OFFSET + VOXEL_V_BITS)
#define VOXEL_X_MASK ((1 << VOXEL_X_BITS) - 1)
#define VOXEL_Y_MASK ((1 << VOXEL_Y_BITS) - 1)
#define VOXEL_Z_MASK ((1 << VOXEL_Z_BITS) - 1)
#define VOXEL_U_MASK ((1 << VOXEL_U_BITS) - 1)
#define VOXEL_V_MASK ((1 << VOXEL_V_BITS) - 1)
#define VOXEL_DIRECTION_MASK ((1 << VOXEL_DIRECTION_BITS) - 1)